export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_POST = 'FETCH_POST';
export const LIKE = 'LIKE';
export const COMMENT = 'COMMENT';
export const END_LOADING_POST = 'END_LOADING_POST';
export const START_LOADING_POST = 'START_LOADING_POST';
export const ONE_POST_LOADING = 'ONE_POST_LOADING';
export const ONE_POST_END_LOADING = 'ONE_POST_END_LOADING';
export const PUBLIC_WAITING = 'PUBLIC_WAITING';
export const TOP_POST = 'TOP_POST';
export const WAITING_POSTS = 'WAITING_POSTS';
export const PUBLIC_POSTS = 'PUBLIC_POSTS';
export const ARCHIVED_POSTS = 'ARCHIVED_POSTS';
export const POSTS_ARCHIVED = 'POSTS_ARCHIVED';
export const POSTS_UNARCHIVED = 'POSTS_UNARCHIVED';
export const LIST_LIKE_POSTS = 'LIST_LIKE_POSTS';
export const LIST_My_POSTS = 'LIST_My_POSTS';


export const FETCH_CHAT_POST = 'FETCH_CHAT_POST';
export const CREATE_CHAT_MESSAGE = 'CREATE_CHAT_MESSAGE';
export const END_LOADING_CHAT = 'END_LOADING_CHAT';
export const START_LOADING_CHAT = 'START_LOADING_CHAT';


//ORDER
export const END_LOADING_ORDER = 'END_LOADING_ORDER';
export const START_LOADING_ORDER = 'START_LOADING_ORDER';
export const DETAIL_ORDER = 'DETAIL_ORDER';
export const LIST_ORDERS = 'LIST_ORDERS';
export const CREATE_ORDER = 'CREATE_ORDER';
export const EDIT_ORDER = 'EDIT_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';









//USERS
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const LIST_USERS = 'LIST_USERS';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const END_LOADING_USER = 'END_LOADING_USER';
export const START_LOADING_USER = 'START_LOADING_USER';
export const PROFILE = 'PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const EDIT_PROFILE = 'EDIT_PROFILE';

//products
export const LIST_PRODUCTS = 'LIST_PRODUCTS';
export const ONE_PRODUCT = 'LIST_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const END_LOADING_PRODUCT = 'END_LOADING_PRODUCT';
export const START_LOADING_PRODUCT = 'START_LOADING_PRODUCT';
export const ONE_PRODUCT_LOADING = 'ONE_PRODUCT_LOADING';
export const ONE_PRODUCT_END_LOADING = 'ONE_PRODUCT_END_LOADING';